apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
      annotations:
        iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpServiceAccount }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: BACKEND_SERVICE_URL
