apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-db-secrets
  namespace: todo-webapp
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-db-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: db-host
        version: latest
    - secretKey: DB_PORT
      remoteRef:
        key: db-port
        version: latest
    - secretKey: DB_NAME
      remoteRef:
        key: db-name
        version: latest
    - secretKey: DB_USER
      remoteRef:
        key: db-user
        version: latest
    - secretKey: DB_PASSWORD
      remoteRef:
        key: db-password
        version: latest
