name: Create Release Branch

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: stone-botany-440911-u3
  REGION: asia-northeast1
  GAR_LOCATION: asia-northeast1-docker.pkg.dev/stone-botany-440911-u3/devops-webapp/

jobs:
  create-release-branch:
    name: Create and Push Release Branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Get Image Tags from Latest Build
      id: get-tags
      run: |
        # Extract the image tag (SHA) from the last commit
        BACKEND_TAG=$(git rev-parse --short HEAD)
        FRONTEND_TAG=$(git rev-parse --short HEAD)

        echo "backendTag=${BACKEND_TAG}" >> $GITHUB_ENV
        echo "frontendTag=${FRONTEND_TAG}" >> $GITHUB_ENV

    - name: Update Helm values.yaml
      run: |
        sed -i "s|tag:.*|tag: \"${{ env.backendTag }}\"|g" deployment/helm/templates/values.yaml
        sed -i "s|tag:.*|tag: \"${{ env.frontendTag }}\"|g" deployment/helm/templates/values.yaml

    - name: Create a Release Branch
      run: |
        RELEASE_BRANCH="release/v${{ github.run_id }}"
        git checkout -b $RELEASE_BRANCH
        git add deployment/helm/templates/values.yaml
        git commit -m "Update image tags in values.yaml for release $RELEASE_BRANCH"
        git push origin $RELEASE_BRANCH
