name: Terraform Workflow

on:
  push:
    paths:
      - 'terraform/**'
    branches:
      - '**'
  pull_request:
    paths:
      - 'terraform/**'

jobs:
  terraform:
    name: Terraform Actions
    runs-on: ubuntu-latest

    env:
      TF_LOG: WARN
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        run: |
          echo "${{ secrets.GCP_IAC_SA_KEY }}" > $HOME/GCP_IAC_SA_KEY.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/GCP_IAC_SA_KEY.json
          gcloud auth activate-service-account --key-file=$HOME/GCP_IAC_SA_KEY.json

      - name: Debug Service Account Key
        run: |
          echo "Validating the JSON Key File"
          cat $HOME/GCP_IAC_SA_KEY.json

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        if: github.event_name != 'push' || github.ref != 'refs/heads/main'
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: terraform
        run: terraform apply -auto-approve
