name: Terraform Workflow

on:
  push:
    paths:
      - 'terraform/**'
    branches:
      - '**'
  pull_request:
    paths:
      - 'terraform/**'

jobs:
  terraform:
    name: Terraform Actions
    runs-on: ubuntu-latest

    env:
      TF_LOG: WARN
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set working directory
        run: cd terraform/

      - name: Authenticate with GCP
        id: auth
        run: |
          echo "${{ secrets.GCP_IAC_SA_KEY }}" > GCP_IAC_SA_KEY.json
          export GOOGLE_APPLICATION_CREDENTIALS="GCP_IAC_SA_KEY.json"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

#      - name: Cache Terraform Plugins
#        uses: actions/cache@v3
#        with:
#          path: ~/.terraform.d/plugin-cache
#          key: ${{ runner.os }}-terraform-plugins

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        if: github.event_name != 'push' || github.ref != 'refs/heads/main'
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: terraform
        run: terraform apply -auto-approve
