name: Terraform Workflow

on:
  push:
    paths:
      - 'terraform/**'
    branches:
      - '**'
  pull_request:
    paths:
      - 'terraform/**'

jobs:
  terraform:
    name: Terraform Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_IAC_SA_KEY }}"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        if: github.event_name != 'push' || github.ref != 'refs/heads/main'
        working-directory: terraform
        run: terraform plan -no-color -out=tfplan

      - name: Debug Plan File
        if: github.event_name != 'push' || github.ref != 'refs/heads/main'
        working-directory: terraform
        run: |
          echo "Checking if tfplan file exists:"
          ls -lah tfplan || exit 1

      - name: Output Full Plan (JSON)
        if: github.event_name != 'push' || github.ref != 'refs/heads/main'
        working-directory: terraform
        run: |
          terraform show -json tfplan > plan.json
          cat plan.json | jq .
